CREATE TABLE IF NOT EXISTS notulen_rapat (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tanggal_rapat DATE NOT NULL,
    topik VARCHAR(200) NOT NULL,
    hasil_keputusan VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
